### ISSUE TITLE
As a Regsitrar I want to be notified if a record i tried to register from a new application I created myself is a potential duplicate

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4443] opened 2022-12-12 14:57 UTC
### Description
- adds Toast message if record is a duplicate

### Acceptance criteria

GIVEN there is a potential duplicate
THEN move the record to Ready for review
THEN show Toast message

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10864%3A83039&t=bVvysRXDt9MgtZe2-1

### Dev tasks

- [ ] Task 1

**Comment by anny320** [comment] 2023-02-02 11:32
@Zangetsu101  please update the Copy of the duplicate flag in the review page to read " .... Potential duplicate of…. " instead of "with"  replace the word  with to **of**

**Comment by SyedaAfrida** [comment] 2023-03-27 06:51
@anny320 this ticket is fixed and can be closed
https://www.loom.com/share/b4ecc10886f548cb94abbf1f13066d45

**Comment by anny320** [comment] 2023-04-06 16:07
completed

**Closed by anny320** 2023-04-06 16:08 UTC
