### ISSUE TITLE
Updating an In Progress application deletes it in a particular case 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1903] opened 2020-08-07 10:36 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an application and save and exit without filling information
2. Click update from In Progress tab 
3. Click change from Main Contact 
4. Click Exit without making any changes
5. Application gets deleted from in progress tab

**Expected behaviour**
Application should not get deleted 

**Screenshots**
![1903_1](https://user-images.githubusercontent.com/44313971/89638047-fdba6280-d8cc-11ea-8157-0ba0138146cc.JPG)

![1903_2](https://user-images.githubusercontent.com/44313971/89638054-feeb8f80-d8cc-11ea-8655-db3d0be7c35f.JPG)

![1903_3](https://user-images.githubusercontent.com/44313971/89638057-ff842600-d8cc-11ea-8d7a-5b4d17a42e04.JPG)

![1903_4](https://user-images.githubusercontent.com/44313971/89638060-001cbc80-d8cd-11ea-8eea-8b6d1e577e01.JPG)

![1903_5](https://user-images.githubusercontent.com/44313971/89638062-00b55300-d8cd-11ea-8952-d62bfebc5a3f.JPG)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by SabitIbnAliKhan** [comment] 2020-08-13 13:25
Only exiting from mentioned page deletes the application.

**Comment by anninawersun** [comment] 2020-08-20 14:48
Need to clarify - is the user starting the application and answering the preliminary qs or not? The application is only saved once they reach the child's details page.

**Comment by euanmillar** [comment] 2021-11-01 20:10
Closing as this is a duplicate of: https://github.com/opencrvs/opencrvs-core/issues/2213

**Closed by euanmillar** 2021-11-01 20:10 UTC
Labels: 👹Bug, Priority: low
