### ISSUE TITLE
Cannot see the full calendar in Audit option

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#1971] opened 2020-08-25 09:26 UTC
**Describe the bug**
When using the Audit option in Team tab, user cannot see the whole calendar when selecting a time frame 

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Sysadmin 
2. Click on Team 
3. Go to an User details 
4. Select the time frame selection option
5. Notice the entire calendar does not show on screen 

Please note that for larger monitors, the calendar can be seen 

**Expected behaviour**
Calendar should appear fully despite monitor size 

**Screenshots**
Please refer to the video to see the issue 
https://www.loom.com/share/b20602c241ac40368bb9bb6fa7ce88c9

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 84.0.4147.105

**Comment by euanmillar** [comment] 2021-11-01 20:34
Closing as duplicate of: https://github.com/opencrvs/opencrvs-core/issues/1946

**Closed by euanmillar** 2021-11-01 20:34 UTC
Labels: 👹Bug, Priority: low
