### ISSUE TITLE
Configuration of custom system roles 

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4101] opened 2022-10-17 13:00 UTC
### **Problem statement**

Ability of a sys admin to enable custom permissions for a user 
configuration of user roles: this would involve the creation of custom roles to which permissions (or groups of permissions) could be applied e.g. notify/declare, validate, register, certify, correct, search, certified copy etc. Another aspect would be the administrate scope of their work queues / performance management e.g. office / District / State / National
### **Proposed work**

(High-level overview of what we're building and why we think it will solve the problem).

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

-

### **Scope**

(Current requirements)

### **Future work**

(Future requirements)

**Comment by euanmillar** [comment] 2024-01-22 16:14
Duplicate of #6455

**Closed by euanmillar** 2024-01-22 16:14 UTC
Labels: Feature
