### ISSUE TITLE
Create profile of individuals across their life

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1819] opened 2020-06-24 12:20 UTC
### **Problem statement**

Need to be able to view all life events and family relationships of a person

### **Proposed work**

TBC

### **Success criteria**

TBC

### **User stories**

TBC

### **Scope**

See Notion ticket

### **Future work**

(Future requirements)

**Comment by jpye-finch** [comment] 2023-10-18 11:09
closing as duplicate of #3947

**Closed by jpye-finch** 2023-10-18 11:09 UTC
Labels: ⭐️ Epic, Backlog
