### ISSUE TITLE
Digital signature configuration

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3944] opened 2022-09-16 12:12 UTC
### **Problem statement**
Currently in default configuration Digital signatures are used if printing and issuing, and wet signature(blank space) if printing in advance. Digital signature regulations vary from country to country so we need to provide a configuration option to give a National System Admin control of how digital signatures can be applied. 

### **Proposed work**

Need to allow a NSAdmin to config how digital signatures used in their country:
- Only digital signatures
- Only wet signatures
- "Printer'er" can choose with or without
- Digital if printing and issuing, wet if printing in advance

**Comment by eduffus** [comment] 2024-01-23 08:46
I have marked this as low priority as we already have quite a lot of flexibility by being able to turn on/off digital sigs and having the ability to include or not using the handlebars of the cert.

**Comment by euanmillar** [comment] 2024-11-25 13:21
Duplicate of country request #6905 #6907

**Closed by euanmillar** 2024-11-25 13:21 UTC
Labels: Feature
