### ISSUE TITLE
Proof of Birth Field: Uploaded File Not Replacing Previous File

### ISSUE THREAD

**Issue by onnee04** [opencrvs/opencrvs-core#7424] opened 2024-07-31 05:49 UTC
**Bug description:**
Proof of Birth Field: Uploaded File Not Replacing Previous File

**Steps to reproduce:**

- Login as Field Agent
- Declare a birth event
- Provide child, informant, mother's details
- Land on "Upload supporting documents" page
- upload "proof of birth". Selected file will be uploaded. 
- Again click on upload for "proof of birth"
- Select another file for "proof of birth"
- click on "Continue"

**Actual result:**
Uploaded file not replacing previous one. User have to remove the previous one and have to upload a new one.

**Expected result:**
Recently uploaded file should replace the previous one.

**Screenshot/ Recording:**

![Image](https://github.com/user-attachments/assets/b1f20174-383b-4072-906b-3fa2adb63c84)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Version:**
V1.6.0

**Comment by Zangetsu101** [comment] 2024-08-01 06:27
@jpye-finch Which one would be a good UX? let the user replace the previous one by uploading again or disabling the upload button?

**Comment by jpye-finch** [comment] 2024-08-01 06:35
@Zangetsu101 
i would expect when you click upload. It uploads another document

It is not a bug imo

This ticket adds the ability to add multiple: https://github.com/opencrvs/opencrvs-core/issues/6516
- Notification of births
- Notification of births #2

**Comment by Zangetsu101** [comment] 2024-08-01 08:22
cool, thanks!

**Comment by tiri39** [comment] 2024-08-07 11:45
Similar issue found in the signature section for marriage declarations - 

Signature is not getting replaced after updating.


https://github.com/user-attachments/assets/df7c9b70-d2eb-4895-a499-8ace728a5ee5

**Comment by euanmillar** [comment] 2024-08-12 08:57
@jpye-finch @onnee04 as this is not critical I will be suggesting making it low priority and removing it from the release.

**Comment by euanmillar** [comment] 2024-08-12 09:44
We decided in project management call that this is not a bug, so we are closing it

**Closed by euanmillar** 2024-08-12 09:44 UTC
Labels: Bug
