### ISSUE TITLE
Occasionally, record audit page reloads and sometimes goes blank after showing page details

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#3500] opened 2022-06-16 10:50 UTC
**Describe the bug**
Application page reloads after showing page details

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as Registrar
2. Click on pagination and select any page number
3. Click on any application
4. See First open(status:Registered)> Reload >open(Status: Certified)
 

**Expected behaviour**
record audit page shouldn't be reload after open.
status shouldn't be inconsistance.
**Actual Result**
https://www.loom.com/share/282fcc63945d4aa3875b5df0a46b645f

https://images.zenhubusercontent.com/91778759/fce3a21a-f004-467d-a29f-ca9d5774326f/records__status.mp4

**Comment by soumita-dsi** [comment] 2022-06-17 08:44
Should be fixed by merging this PR https://github.com/opencrvs/opencrvs-core/pull/3506

**Comment by euanmillar** [comment] 2022-06-20 09:40
@soumita-dsi can you check the filtering on the workqueue.  There should be no Certified applications in the Ready To Print workqueue

**Comment by soumita-dsi** [comment] 2022-06-20 13:13
I checked the workqueue filtering and I think it's working fine. Also, I am not seeing any application of 'Certified' status in the ''ready to print' tab in my local.  And could not reproduce point no-4.

**Comment by euanmillar** [comment] 2022-06-21 08:20
It is our view that this issue is caused somehow by the test data.  The test data has Certified applications in the Ready To Print workqueue which should not be possible.

**Comment by azantor64** [comment] 2022-06-22 11:49
@anny320 , This problem is not appearing in newly deployed server.it can be closed.

**Comment by anny320** [comment] 2022-06-23 10:17
completed

**Comment by anny320** [comment] 2022-06-23 10:17
completed

**Closed by anny320** 2022-06-23 10:17 UTC
Labels: 👹Bug, Priority: medium
