### ISSUE TITLE
Name fields should support (') apostrophe

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4715] opened 2023-02-20 12:08 UTC
**Bug Description :**
Name fields should support special characters like (' , - and .). Currently we support- and . Need to support apostrophe also
Also applicable for user names

**Steps to reproduce:**
1. Login to FA/ RA/ local or national registrar
2. Declare a birth/ death event
3. Observe name fields

**Actual result:**
Do not support Aspostrophe '

**Expected result:**
Name fields should support (') apostrophe

**Screenshot:**
![aa.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/16112597-f9ee-423f-84d9-06443844f099)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by Zangetsu101** [comment] 2023-03-30 08:46
Duplicate of #4763

**Closed by Zangetsu101** 2023-03-30 08:46 UTC
Labels: 🧬 Improvement
