### ISSUE TITLE
Changes in name not getting reflected in Ready for Review and Sent for Updates tab 

### ISSUE THREAD

**Issue by SabitIbnAliKhan** [opencrvs/opencrvs-core#2034] opened 2020-10-15 13:22 UTC
**Describe the bug**
When user downloads and updates the name from Ready for Review and Sent for Updates tab, the change is not getting reflected on the application after pressing Save and Exit.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Ready for Review
2. Download an application 
3. Click Review > Change name of Child /  Deceased 
4. Click Save and Exit 
5. Change in name is not reflected 

Steps to reproduce the behaviour:
1. Go to Sent for Update 
2. Download an application 
3. Click Update > Change name of Child /  Deceased 
4. Click Save and Exit 
5. Change in name is not reflected 

**Expected behaviour**
Change in name should reflect 

**Screenshots**
https://www.loom.com/share/0b9588b632b647ae92719e1ca073b55f

**Comment by euanmillar** [comment] 2021-11-01 20:46
Closing as unclear

**Comment by anninawersun** [comment] 2021-11-02 12:01
@euanmillar i think we need to re-open this. The Loom is clear to me - let's discuss.

**Comment by euanmillar** [comment] 2021-11-26 09:59
@SyedaAfrida is this a duplicate of this one?

https://github.com/opencrvs/opencrvs-core/issues/2163

**Comment by SyedaAfrida** [comment] 2021-11-26 10:09
@euanmillar yes both of these issues seems same to me

**Closed** 2021-12-17 09:38 UTC
Labels: 👹Bug, Priority: medium
