### ISSUE TITLE
feat: Supervisory Offices

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4925] opened 2023-03-24 09:31 UTC
### Description
- Adds supervisory offices to Core. (Same as what added to Nigeria)
- A supervisory office has a combined workqueue view of all child locations plus records started in the supervisory office. 

For another ticket maybe?:
- In Cameroon Field Agents will work in a Hospital. 
- Updates the location ref data to include Registration offices and Health Institution.
- Given I am creating a new user I can assign them to an Health Institution
- All locations including the Health institutions appear in the Organisation view  
- All locations have a team page

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/5528a8db-68df-45c0-9fc1-2496ba6146c8)

### Acceptance criteria

GIVEN I a Reg Agent, Registrar or National Registrar
WHEN I am assigned to a Supervisory Office
THEN I a combine list of records for workqueues in my office and all child offices

### Design
(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment] 2024-01-22 16:28
Closing as duplicate of #6454

**Closed by euanmillar** 2024-01-22 16:28 UTC
Labels: Feature
