### ISSUE TITLE
Pre-populate the form & validate a users National ID with MOSIP. Highlight if a National ID has been validated.

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4558] opened 2023-01-12 10:03 UTC
If a declaration is being made and the user is online, they should be able to validate a mothers, fathers, informants & deceased's Natonal ID with MOSIP and pre-populate that page of the form with data returned from MOSIP.

On the review page of any application that has not been registered or on the review page of correct record, the National ID should have an icon to show if it has been validated or not.

If a registrar, field agent or reg agent is offline and submits a National ID as part of a form declaration, after it goes through the Outbox, we need to check if all supplied National IDs are valid.  If any are invalid, the application should be rejected and the specific National ID highlighted.  In Record Audit, the rejection needs to have been performed by the OpenCRVS system as opposed to by any individual user.

MOSIP do not want us to store a National ID in our database.  If MOSIP is integrated, all National IDs should be removed from the application after it is registered.  National ID therefore should never be allowed to be a mandatory field if MOSIP is integrated.

**Comment by naftis** [comment] 2023-02-13 11:27
Closed as duplicate of #4686

**Closed by naftis** 2023-02-13 11:27 UTC
