### ISSUE TITLE
For field agent, sent for review >audit record page is incorrect for any complete birth application

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3231] opened 2022-05-26 13:42 UTC
**Description:**
For field agent, sent for review >audit record page is incorrect for any complete birth application.

**Steps:**

1. Login as field agent
2. declare a birth event
3. submit an complete birth application
4. goto sent for review page
5. click the application
6. observe audit record page

**Actual Result:**
DOB  is visible and BRN is showing.

**Expected Result:**
BRN shouldn't be in the page and DOB should be hidden.

**ScreenShot:**

![comp_birth.PNG](https://images.zenhubusercontent.com/6281e46d6f51be7532fe12bd/5aebbd2f-5fff-4f97-95e2-be6c8d882428)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by euanmillar** [comment] 2022-05-31 12:06
BRN and DOB should be hidden until after downloading.  But do we really want to not show BRN to a field agent after downloading?  @jpye-finch

**Comment by euanmillar** [comment] 2022-05-31 12:44
Isnt this also a duplicate of this?  https://github.com/opencrvs/opencrvs-core/issues/3244

**Comment by euanmillar** [comment] 2022-05-31 12:45
... and also a duplicate of this: https://github.com/opencrvs/opencrvs-core/issues/3229

**Comment by emon-swe-sust** [comment] 2022-06-01 08:03
Already fixed

**Comment by Fariha-Amin** [comment] 2022-06-02 07:46
@anny320  solved, can be closed

retest SS:
![d](https://user-images.githubusercontent.com/105624748/171580338-4412c35b-646a-4752-a326-82b267261992.PNG)

**Comment by azantor64** [comment] 2022-06-02 07:55
![image](https://user-images.githubusercontent.com/70468099/171581994-3f356d3f-06a7-4083-b617-523917f507be.png)

**Passed** @anny320

**Comment by anny320** [comment] 2022-06-07 07:08
completed

**Closed by anny320** 2022-06-07 07:08 UTC
Labels: 👹Bug, Priority: high, ⛔  Blocked
