### ISSUE TITLE
Add ICD10 coding

### ISSUE THREAD

**Issue by anninawersun** [opencrvs/opencrvs-core#1828] opened 2020-06-24 14:22 UTC
### Description

Research needed on different use cases

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Copy

(Link to Notion)

### Dev-tasks??

- [ ]  Task 1

**Comment by euanmillar** [comment] 2021-11-01 19:55
Closing as it is a duplicate of: https://github.com/opencrvs/opencrvs-core/issues/1837

**Closed** 2022-06-28 07:58 UTC
