### ISSUE TITLE
Comms: Send a email to all users

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6359] opened 2023-12-11 12:06 UTC
### Description
Place holder ticket to let a National System admin send an email to all users

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by euanmillar** [comment] 2024-01-22 16:31
Closing as duplicate of #6410

**Closed by euanmillar** 2024-01-22 16:31 UTC
Labels: Feature
