### ISSUE TITLE
A old record cannot be downloaded after a configuration change is made

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4412] opened 2022-12-06 11:39 UTC
**Bug description:**
A old record cannot be downloaded after a configuration change is made
**_Note_:** If death is configured, then birth records created with old configuration cannot be downloaded. Same thing happens with death

**Steps to reproduce:**
1. Login as FA/ RA/ Registrar
2. Create a birth/ death record
3. Logout
4. login as National system admin
5. Click Configuration> Declaration form
6. Click Configure> Create a custom field> Save
7. Click 3 dot menu> preview
8. Logout
9. Login to RA/ Registrar
10. Click download to assign to that old record

**Actual result:**
download fails
![err.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/b610330b-8065-4b0b-b5c5-41bdd8167758)

**Expected result:**
after configuration change is made old record should not appear in workqueue

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by euanmillar** [comment] 2022-12-16 13:39
This may be  functioning as designed as previous applications only get deleted when published, but lets take a look

**Comment by euanmillar** [comment] 2022-12-19 09:42
@SyedaAfrida if this happens again, please call @euanmillar  straight away.  Currently we cant reproduce it

**Comment by Zangetsu101** [comment] 2022-12-28 05:49
The issue was with elasticsearch permissions as the search microservice didn't have `delete-index` privilege. Should be fixed in the next deploy

**Comment by SyedaAfrida** [comment] 2023-01-20 10:49
@anny320 This bug is fixed and can be closed 

https://user-images.githubusercontent.com/94350336/213677176-4d845cf0-0f98-4d7a-a432-d60a3eb40d23.mp4

**Comment by anny320** [comment] 2023-01-23 05:43
Completed

**Closed by anny320** 2023-01-23 05:43 UTC
Labels: 👹Bug, 👌Tech OK
