### ISSUE TITLE
Village should be a mandatory field

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3184] opened 2022-05-24 07:22 UTC
**Description:**
Village should be a mandatory field. 

**Steps:**
1.Login as any user except system admins
2. click plus sign to create an application
3. fill necessary information and continue
4. When reached at mothers/fathers/informants  details page, 
    observe the input field by clicking "rural" area.

**Actual Result:**
Village should be a mandatory field

**Expected Result:**
Village isn't  a mandatory field. Can submit application without giving any input.

**Figma Design:**
https://www.figma.com/file/7AYxLlYTpY4RioSTIt0PbG?embed_host=notion&kind=&node-id=0%3A1&viewer=1

**Screenshot:**
![Capture3](https://user-images.githubusercontent.com/105624748/169976525-5ebc7b4d-7e6b-4653-89fa-08840d3d7748.PNG)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Username and password used:**

Username: felix.katongo
Password: test

**Desktop:**
OS: Windows 10
Browser: Chrome

**Comment by anny320** [comment] 2022-05-26 10:37
closing is as it is not a bug, village doesn't need to be a mandatory option

**Closed by anny320** 2022-05-26 10:37 UTC
Labels: 👹Bug, Priority: medium
