### ISSUE TITLE
Handle record submission related errors correctly when an exception is thrown in the country resource package

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6466] opened 2024-01-25 13:52 UTC
When debugging this bug
https://github.com/opencrvs/opencrvs-core/issues/6465

I noticed the issue was completely because an error in the country config package

```
opencrvs_countryconfig.1.8tq1qv3vkprm@farajaland-qa    |     TypeError: ShortUIDGen is not a constructor
opencrvs_countryconfig.1.8tq1qv3vkprm@farajaland-qa    |     at generateTrackingId (/usr/src/app/src/api/tracking-id/service.ts:41:24)
opencrvs_countryconfig.1.8tq1qv3vkprm@farajaland-qa    |     at trackingIDHandler (/usr/src/app/src/api/tracking-id/handler.ts:8:40)
```

## Tech tasks:
- [ ] Make sure client handles errors coming from the backend by keeping the record in outbox
- [ ] Make sure the correct error message gets propagated from country config all the way to gateway

**Comment by rikukissa** [comment] 2024-05-17 07:00
https://github.com/opencrvs/opencrvs-core/issues/7005 duplicate?

**Comment by euanmillar** [comment] 2024-06-03 15:36
Closing as duplicate of #7005

**Closed as completed by euanmillar** 2024-06-03 15:36 UTC
Labels: Tech
