### ISSUE TITLE
Digitisation of Paper Records (Add-on App)

### ISSUE THREAD

**Issue by marcio-opencrvs** [opencrvs/opencrvs-core#7936] opened 2024-11-08 11:29 UTC
## Description

A companion, open-source application built in the countryconfig microservice for use alongside OpenCRVS.

### Pre-requisites before build can commence:

Requires an active, and fully configured OpenCRVS installation to be in place.
Digitisation users will be already created and managed within OpenCRVS.
Uses 1.6 Registration Agent role as the Data Entry Clerk
Uses 1.6 Registrar role as the approving / spot check / digitiser.
Requires Events v2 data model applied to a dedicated “digitsed-records” collection separate from normal registration collections, isolating the digitised records from the 1.6 system until Events V2 is fully functional.
UI components are re-used from OpenCRVS core
Where possible client views are replicated but they could be entirely rebuilt and simplified using base components.  UI design polish will be iterated upon in future phases.  This is an MVP.

### Requirements:

1. The companion application uses OpenCRVS APIs to allow users to log in to see national level workqueues of in-progress, ready for review & requires updates digitised records.
2. Two-factor Authentication and authorization for 2 roles: a) Field Agent - hereby referred to as the “Data Entry Clerk”, b) Registration Agent - hereby referred as “Digitiser”, c) Registrar - hereby referred to as a Spot Check user..
3. The Data Entry Clerk will be able to use easy to navigate event forms to input the legacy data.  These forms will include standardised inputs and data validation for demographics.
4. Standardised inputs will exist on a one-page form to enter all the information required for the legacy event.
5. Input fields will exist to select the original Registrar who registered the record.  First, a search select field allows the user to choose from existing Registrars who are already configured in OpenCRVS as the original Registrar (refer to Registrar mapping note 1).  A checkbox exists if the original registrar cannot be found (e.g. they no longer work here).  If selected a custom field allows the user to type the name of the legacy Registrar (refer to Registrar mapping note 2).
6. A search select allows the user to choose from existing administrative location levels as the place of registration. A checkbox exists if the original place of registration cannot be found (e.g. administrative structure has changed).  If selected, a custom field allows the user to type the name of the legacy administrative location. 
7. A date input field allows the user to enter the date of registration.
8. The Data Entry Clerk will be able to upload image attachments unique to the record such as a scan of the original paper register page.
9. The review page adapts depending on the role.  For Data Entry Clerk, a Send for review button sends the application to the Digitiser for digitisation.  For a Digitiser, a “Digitise” button submits the application for official digitisation. For a Digitiser, a “Reject” button with comments box allows the user to send the application back to the Data Entry Clerk for corrections.
10. Any user can make updates but updates will not be audited.
11. Users will be able to review the record alongside a scan of the original paper record within the user experience of the application, correct any errors or reject the record.
12. An automatic de-duplication algorithm, powered by [ElasticSearch](https://www.elastic.co/elasticsearch), will run to highlight potential duplicates against other legacy records only.  Digitisers will be able to reject or override the de-duplication algorithm as appropriate.
13. A search bar exists, without advanced search, allowing users to search digitised records by name, digitised tracking id (formatted to include date of digitisation: <tracking id>mm-dd-yyyy), date of original registration in mm-dd-yyyy format & registration no.
14. Anyone can download and view a record.
15. Only a Spot Check user can download a record and correct it after digitisation.  Edits will not be audited.
16. The application will be able to be operated for periods of low (interrupted) or no connectivity. Therefore “Outbox”-lite functionality will be included.
17. The digitised data will be backed up on a nightly basis in an encrypted format to a backup server with configurable retention periods.
18. The encrypted backups will be used to migrate the data into the eventual Events v2 flows.  

Registrar mapping note 1: Is it important to audit legacy registrations for existing users of OpenCRVS?  If so the correct user-ids / practitioner ids should connect the digitised record to the existing user.  Future phases could then display legacy audit trail for existing users.

Registrar mapping note 2: If the registrar is no longer active in OpenCRVS, our assumption is that legacy audit trail is not essential.  The data is simply saved as raw text. The purpose is simply historical.

**Comment by euanmillar** [comment] 2024-12-16 09:56
Closing as duplicate of #8137

**Closed by euanmillar** 2024-12-16 09:56 UTC
