### ISSUE TITLE
Marginal notes: Ability to capture marginal notes and print these on subsequent versions of the certificate

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6968] opened 2024-05-10 11:21 UTC
Available for configuration:
- A new page will be added to the form that will only appear post-registration. 
- When a user "corrects the record", they will update this section
- Section on the certificate will show marginal notes 
- Notes are seperate to the digital record

NOTE TO USER IN TRAINING: if you DO NOT update the content of the record and ONLY do this in the marginal note, integration with other systems e.g. ID will not work because OpenCRVS needs to hold the latest and correct version of the record data (not in marginal notes) and share with other systems.

**Comment by jpye-finch** [comment] 2024-07-02 13:54
Suggest using the Comment section to address this. 
https://github.com/opencrvs/opencrvs-core/issues/4253


Note the above can be done in Core today

**Comment by jpye-finch** [comment] 2024-07-30 07:55
Close as duplicate of #4253

**Closed by jpye-finch** 2024-07-30 07:55 UTC
