### ISSUE TITLE
As a Registration Agent/ Registrar/ National Registrar/ Local or National System Admin/ Performance Manager I would like to view Registrations by time, location and registrar

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3853] opened 2022-08-26 06:00 UTC
### Description
- adds registration by time, location and registrar
- adds View button to Total registrations
- <FilterTab> to navigate between views
- [Requirements for the three tables (by time, by location, by registrar)](https://www.notion.so/opencrvs/Registrars-Performance-5e023be4b6b344bc8d6e749baaafce8f)

### Acceptance criteria

GIVEN I am a Registration Agent/ Registrar/ National Registrar/ Local or National System Admin/ Performance Manager
WHEN I navigate to the performance page
THEN I can see a View link next to Total registrations

GIVEN I am a Registration Agent/ Registrar/ National Registrar/ Local or National System Admin/ Performance Manager
WHEN I click View next to Total registrations
THEN navigate to the the Registrations performance page

---

GIVEN I am on the Registrations performance page
WHEN I change the event
THEN update the table to reflect the event data

GIVEN I am on the Registrations performance page
WHEN I change the time period
THEN update the table to reflect my chosen time period

GIVEN I am on the by time tab
WHEN I change the location to an office
THEN disable the by locations tab

--

GIVEN I am on the Registrations performance page
WHEN I click By locations 
THEN update the table to the By locations

GIVEN I click on a Location link ( in the table )
THEN navigate to that Location Performance Dashboard page

GIVEN I on the By location tab
WHEN I change my location to an office level
THEN default to By time and disable the by locations tab

---

GIVEN I am on the Registrations performance page
WHEN I click By registrars 
THEN update the view to the by registrar table

GIVEN I click on a Registrar link ( in the table )
THEN navigate to that users User Audit page

---

GIVEN there are no results
THEN [show no results view](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7571%3A16159)

GIVEN there are more than 10 row items
THEN show pagination

GIVEN I hover over a percentage figure
THEN [show the total in a tooltip ](https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7432%3A9898)

---
**Death**
GIVEN I change the event type to Death
THEN I don't see the late registration column

### Design
Table requirements: https://www.notion.so/opencrvs/Registrars-Performance-5e023be4b6b344bc8d6e749baaafce8f
Design: https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7432%3A9377

### Dev tasks
- [x] In metrics, generateBirthRegPoint saves the practitionerRole.  The practitionerRole is the role type for the person who started the application. It is used in other metrics requests.  We need to save the information of the registrar.  We should save the practitionerId for the registrar, call it registrarPractionerId - 1

- [x] In packages > client > views > Performance we need to make a new view that is similar to FieldAgentList, lets call it RegistrationsList.  It will have a similar layout.  Layout the table with dummy data, pagination. - 2
- [x] Registrar option: In metrics, gateway and client, getTotalMetrics query needs an optional parameter to return all rows from metrics as opposed to just the count, then use a type-resolver to return the registrar's name and userId using the registrarPractionerId. - 3

- [x] Location option: In metrics, gateway and client, getTotalMetrics query needs an optional parameter to behave like locationWiseEventEstimations used in Completeness Rates, so that we can get all child location metrics from the parent location, e.g. all states in Farajaland in a single row - 3

- [x] By Time option: In metrics, gateway and client, getTotalMetrics query needs an optional parameter to group the registrations by the month, e.g. all registrations per month in a single row - 3

- [x] Create functions to sort the table rows - 2
- [x] Layout the SegmentedControl, Location Picker, Date range select, PerformanceSelect (birth / death) with action functions to call the queries and populate with real data (save the states in URL parameters) - 3

### Breaking change

- [x] We need a migration to loop through all compositions that have businessStatus.coding.code equal to REGISTERED and get the practitionerId for the regLastUser and update the birth_registration measurement with the practitionerId - 3

**Comment by anny320** [comment] 2022-09-16 08:19
![Screenshot 2022-09-16 at 09.49.44.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/8412fa1c-4f84-49c4-9adb-2d7e7eee0ddc) something like this

**Comment by euanmillar** [comment] 2022-09-26 08:56
@jpye-finch I dont understand what the expected behaviour is by using these buttons.. ![Screenshot 2022-09-26 at 09.51.10.png](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/2a0e96b8-f31f-42e4-b2d0-1efe4bb84ddd). Could that be explained in acceptance criteria vs the separate location finder and date range UI components?

I do not understand the benefit of showing delayed and late registrations when it is entirely the responsibility of the parent to register in time.  How is that related to registrar performance?

**Comment by euanmillar** [comment] 2022-10-03 13:12
@anny320 the user role permissions in the notion doc as to which user can use the location filter for searching other locations need to be added as acceptance criteria for Syeda's test cases.  @jpye-finch we need a design from the performance page with the view link that launches this page in the Figma.  Also if the time period covered multiple years, how would we concatenate month and year in the month column label?  I notice Location # and Registrar name # are links.  The behaviour of these links needs explanation in the AC

**Comment by jpye-finch** [comment] 2022-10-03 13:22
add ACs for the location and registrar links

**Comment by jpye-finch** [comment] 2022-10-03 13:23
the Dashboard page with the View link. is to the left of the Registration screens https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=7432%3A10964

**Comment by jpye-finch** [comment] 2022-10-03 13:27
good point on the Months. Do that same as we do in the line graph?
<img width="755" alt="image" src="https://user-images.githubusercontent.com/46478402/193589133-8e593429-5cfc-4cbc-9ee3-ccf0219bebe0.png">

So every January shows the year
<img width="505" alt="image" src="https://user-images.githubusercontent.com/46478402/193589239-3a7d355e-fc40-4d52-80fc-416a6b7311e3.png">

**Comment by euanmillar** [comment] 2022-10-07 11:18
@jpye-finch @anny320 @eduffus  the columns "Home, "Health Facility", are not enough as there is also an "Other" type.  I wonder what home and health facility actually tell us regarding registrar performance.  Is this not more of a vital statistic that health statisticians could retrieve with VSExport?  I think that we could make this simpler by removing these columns, especially when we consider that Nigeria are starting to track types of "Other" birth location, e.g. ROADSIDE.

**Comment by SyedaAfrida** [comment] 2022-12-12 11:39
**Bug:**
1. column name wrong when filtered with death
![column name wrong when filtered with death](https://user-images.githubusercontent.com/94350336/207035093-f862be28-d4a9-471f-ac2d-a5e8906adf6e.png)

2. profile icon missing beside Registrar and Username and location should be clickable links
![profile icon missing beside Registrar and Username and location should be clickable links](https://user-images.githubusercontent.com/94350336/207035230-70b73e0b-5cd7-415f-9f1d-38278c970e7b.png)

3. pagination overlapping with tableview component
![pagination overlapping with tableview component](https://user-images.githubusercontent.com/94350336/207035386-74a7162f-088e-4ab2-b9f8-eef8f2a40464.png)

4. no records showing in home death of performance when location is ibombo district/ office/ farajaland

https://user-images.githubusercontent.com/94350336/207035684-82a5ccad-47c2-4d09-9bc2-4a0c069c91aa.mp4

5. home death and health facility death value is always 0 when searched for a different office 

https://user-images.githubusercontent.com/94350336/207035778-c3e4f27f-f8e4-4fbe-a6b4-25729d5925cf.mp4

6. Mobile view is broken
![mobile view is broken](https://user-images.githubusercontent.com/94350336/207036049-022d9c29-f025-48a5-9422-03ef9e453f8b.png)

**Comment by CornelMaze** [comment] 2022-12-15 07:33
@SyedaAfrida Concerning bug 4. How do we know that the death reg is in November, because the registration says December and you can only get December records after that month or am I missing something?

**Comment by CornelMaze** [comment] 2022-12-15 07:35
@SyedaAfrida The same thing applies to bug 5.

**Comment by SyedaAfrida** [comment] 2022-12-15 09:21
@CornelMaze I have removed those bugs(4,5) and update with the new bug (4). Please have a look to that.

**Comment by euanmillar** [comment] 2022-12-16 09:36
For the group by month problem, the query is coded to look for 30 day increments so that needs to change.  Needs some tech design

**Comment by euanmillar** [comment] 2022-12-19 19:46
Hi @SyedaAfrida and @anny320  the developers say that we split the months up into 30 day groups.  Sometimes registrations made at the end of the month may fall into the previous or later month for this reason.  It seems we might have to upgrade influxdb to version 1.8 or above in other to utilize flux query to solve the group by month issue.  This would mean that all the metrics would need regression tested so I think a fix for this new bug 4 must be in a new ticket that we could address in v1.3.

**Comment by SyedaAfrida** [comment] 2022-12-20 07:48
@euanmillar @anny320 created a new ticket #4482  for bug (4)

**Comment by SyedaAfrida** [comment] 2022-12-27 06:43
@Zangetsu101 a new ticket is created for bug (4) #4482 and the rest of the bugs are not fixed. So moving this ticket back to to-do

**Comment by Zangetsu101** [comment] 2022-12-28 05:58
Removing the blocked label as we have #4482 for the blocker

**Comment by alamin-7** [comment] 2023-01-02 11:55
**Design issue:**
Delayed registrations drop-down button is not in exact position mobile view as well. Otherwise all are ok.

**Screen record:**
[3853.webm](https://user-images.githubusercontent.com/38520477/210227945-cf146321-360d-4cbf-880b-f2a9776e575f.webm)

**Comment by alamin-7** [comment] 2023-01-04 10:00
@jpye-finch This is the current state and we do not have any overlap issue now. But as we do not have any design for this, we are setting the status as passed.

**Comment by jpye-finch** [comment] 2023-01-16 13:43
Please note the actions done on a record. Should be exactly the same as those in Record Audit. Need to ensure the copy is the same and the same content is shown in the model.

https://www.notion.so/opencrvs/632eb35dbb4e43bb97e3927c8640ff7d?v=38f05b50daf7428cb8cde2f9a08372d8

**Comment by anny320** [comment] 2023-01-23 05:46
Completed

**Closed by anny320** 2023-01-23 05:46 UTC
