### ISSUE TITLE
Replace radio buttons to check box in birth form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3059] opened 2022-05-13 09:19 UTC
**Bug description:**
Few radio buttons needs to be replaced to check box in birth form.

**Steps to reproduce:**
1. Create a birth event
2. Select " Who is applying for birth registration?" anyone except Mother /father
3. Go to mother's details page
4. Go to father's details page

**Actual result:**
Do you have the mother's details? / Do you have the father's details? - are radio button questions
In father's details page> "Same as mother's usual place of residence?"  -  are radio button questions

**Expected result:**
Do you have the mother's details? / Do you have the father's details? - should be checkbox questions
In father's details page> "Same as mother's usual place of residence?" - should be checkbox questions

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by anny320** [comment] 2022-06-07 15:35
postponed for future fixes

**Comment by euanmillar** [comment] 2022-06-29 15:32
Closing as duplicate of: https://github.com/opencrvs/opencrvs-core/issues/3126

**Closed by euanmillar** 2022-06-29 15:32 UTC
Labels: ⛔  Blocked, 🧬 Improvement
