### ISSUE TITLE
As a Registrar or Reg Agent I want to issue a certificate printed in advance

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4356] opened 2022-11-28 11:12 UTC
### Description
- We need to audit the issuance of a certificate
- Adds a new workqueue 'Ready to issue'
- If a certificate is printed in advance the record is moved to this work-queue
- Capture who is collecting, ID check if informant
- Payment collection and print reciept

### Acceptance criteria

GIVEN I print a certificate in advance
WHEN I click confirm
THEN change the record status to Certified and move to Ready to Issue

GIVEN a record is in the Ready to issue work-queue
WHEN I click Issue
THEN navigate to the Issue certificate workflow

GIVEN I select Issue to informant
THEN navigate to the ID Check

GIVEN I select Issue to someone else
THEN navigate to the Collector details

GIVEN I have checked the id or captured the collector details 
THEN navigate to Collect payment 

GIVEN I click Issue certificate
THEN move the record to the Outbox and update the record audit

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=9434%3A79898&t=4VbkamxwtyZTwWnj-1

### Dev tasks

- [ ] Create a new workqueue "Ready to issue" which would show the Certified records. Change the workqueue query as required to accommodate this change. Show the workqueue table according to the design.
- [ ] Add the Issue button in record audit
- [ ] Clicking the issue button should create a new declaration if it's not there already with the status set to CERTIFIED, id set from the workqueue data.
- [ ] Create a new issue certificate flow similar to print certificate flow. Create a Collector form which would take the details if someone else is selected.
- [ ] Build the proof of ID view, show modal if no id match selected.
- [ ] Show the collect payment view with the appropriate fee according to the registration delay
- [ ] Clicking issue Certificate would set the action of the declaration to be ISSUE_CERTIFICATE from #4355

**Comment by Zangetsu101** [comment] 2023-01-31 06:34
Duplicate of #4357

**Closed by Zangetsu101** 2023-01-31 06:34 UTC
