### ISSUE TITLE
In birth declaration, "Do you have the mother's details? "question should not appear when the informant is father

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3013] opened 2022-05-09 13:36 UTC
**Bug description:**
In birth declaration, "Do you have the mother's details? "question should not appear when the informant is father

**Steps to reproduce:**
1. declare a birth event
2. In "Who is applying for birth registration?" select father
3. Go to mother's details page

**Actual result:** 
"Do you have the mother's details? "question appears

Expected result:
"Do you have the mother's details? "question should not appear

**Screenshot:**
![mother's details.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/f9b4ac4b-69bb-4417-a2f1-5e8def05e88c)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment] 2022-05-10 10:27
I dont think that is right.  @jpye-finch to speak to Ed

**Comment by jpye-finch** [comment] 2022-05-19 10:56
Confirmed. Not a bug.

**Comment by jpye-finch** [comment] 2022-05-19 10:57
but should be a Checkbox
https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/3126

**Comment by euanmillar** [comment] 2022-05-19 14:18
Closing this in favour of: https://github.com/opencrvs/opencrvs-core/issues/3126

**Closed by euanmillar** 2022-05-19 14:18 UTC
Labels: 👹Bug, Priority: high, ⛔  Blocked
