### ISSUE TITLE
Console error for all users

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#4773] opened 2023-02-28 13:25 UTC
**Bug description:**
Console error for all users

**Steps to reproduce:**
1. Login as any user and observe console

**Actual result:**
User can see console errors

**Expected result:**
Errors must be resolve

**Screenshot:**
![con1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/2c8be9cd-4081-4eb1-ba71-1a32910b2144)
![con2.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/e9dad6d0-66b2-49cc-acd5-3416a3c554f4)

Updated error
![updated console error](https://user-images.githubusercontent.com/94350336/223100371-e87f8bc4-4ec3-4c9e-bd13-8844d5a2ad47.png)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment] 2023-03-14 09:08
apollo-cache-persist error is fixed now. And the other "minified react error" is possibly caused by "loom" extension: https://stackoverflow.com/a/75607659

**Comment by anny320** [comment] 2023-03-15 06:22
Complete![Screenshot 2023-03-15 at 09.21.23.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/dcf21c56-bbdc-49d0-a25c-4b4f8ebafd3a)d

**Closed by anny320** 2023-03-15 06:22 UTC
Labels: 👹 Bug, 👌Tech OK
