### ISSUE TITLE
Replace Radiobutton to checkbox in Death form

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3060] opened 2022-05-13 09:29 UTC
**Bug description:**
Few radio buttons needs to be replaced to check box in death form.

**Steps to reproduce:**
1. Create a death event
2. Go to death details page
3. Go to informant details page

Actual Result:
1. In death details: "Has a cause of death been established?" -  are radio button questions
2.  In informant details: "Same as deceased's usual place of residence?"-  are radio button questions

**Expected result:**
1. In death details: "Has a cause of death been established?" - should be checkbox questions
2.  In informant details: "Same as deceased's usual place of residence?"- should be checkbox questions 

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment] 2022-06-21 08:31
As per the birth form issue, we will not do this in this release

**Comment by euanmillar** [comment] 2022-06-29 15:32
Closing as duplicate of: https://github.com/opencrvs/opencrvs-core/issues/3126

**Closed by euanmillar** 2022-06-29 15:32 UTC
Labels: Priority: low, ⛔  Blocked, 🧬 Improvement
