### ISSUE TITLE
Transactional data migrations

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#6253] opened 2023-11-30 11:59 UTC
This ensures that even if something fails when we migrate from one version to next, the records wont in any case end up in inconsistent (corrupted) state. This work has been mostly done already but is still missing some pieces before it actually works.

**Comment by rikukissa** [comment] 2024-01-15 09:08
Duplicate of 
https://github.com/opencrvs/opencrvs-core/issues/4701

**Closed by rikukissa** 2024-01-15 09:08 UTC
Labels: Tech
