### ISSUE TITLE
Performance| Doesn't show the Birth and Death registration rate within 45 days of event

### ISSUE THREAD

**Issue by tamkinmahmud-dsi** [opencrvs/opencrvs-core#2197] opened 2021-07-05 12:25 UTC
**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Reg agent/ registrar
2. Go to Performance page
3. Check the Birth/Death registration rate within 45 days of event in the middle of the page

**Observation**
Rate is showing 0%. Registered Male and Female  are also showing 0%

**Expected behaviour**
Should show the correct rate

**Screenshots**
![Selection_034.png](https://images.zenhubusercontent.com/60b47748c75898083f9b17ec/e6f0d6f1-16ff-4cc4-b440-a6c3aa424b5e)

**Comment by mushrafulhoque-dsi** [comment] 2021-07-12 07:29
Duplicate of 2198

**Closed by mushrafulhoque-dsi** 2021-07-12 07:29 UTC
Labels: 👹Bug
