### ISSUE TITLE
If record is corrected by registrar after registering an application, the update is not visible in performance page

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3245] opened 2022-05-27 12:29 UTC
**Description:**
If record is corrected by registrar after registering an application, the update is not visible in performance page.

**Steps:**
1.Login as any user 
2.click performance and observe percentages and total counts 
3. login as registrar
4. goto ready to print page 
5. click an application and download 
6. click correct record
7. change a data ( EX: change place of birth from home to health institute)
8. goto correction summary page and make correction
9. goto performance page 
10. observe the total counts for the place of births. 

**Actual Result:**
The counts doesn't change for health institute  and home in performance page.

**Expected Result:**
Total count for health institute should have increased by 1 and count for home should be decreased by 1.  Performance page should be updated even when record is corrected after registration. 

**Screen Recording:**

https://user-images.githubusercontent.com/105624748/170701093-84795eff-5bbb-476e-8ff9-15707f2d2f2b.mp4

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by atiqzaman-dsi** [comment] 2022-06-02 10:08
We need to update matrix if something is changed in Correct record.

**Comment by euanmillar** [comment] 2022-06-02 10:17
This is considerable effort for something that we could explain to the user in copy.  E.G. Performance metrics were correct at the moment of registration.  They are immutable analytics that may have had minor changes based on any records corrected after the moment of registration.

**Comment by euanmillar** [comment] 2022-06-02 10:59
@eduffus says we can close this as it is by design. The problem is an edge case.  No copy needed

**Comment by anny320** [comment] 2022-06-14 04:44
closed

**Closed by anny320** 2022-06-14 04:44 UTC
Labels: 👹Bug, Priority: high, ⛔  Blocked
